import pytest
import numpy as np
from gradient_os.ik_backends.ikfast_backend import IKFastBackend

@pytest.fixture(scope="module")
def solver():
    """Pytest fixture to initialize the solver once per test module."""
    try:
        return IKFastBackend()
    except Exception as e:
        pytest.fail(f"Failed to initialize IKFast backend: {e}")

def test_solver_initialization(solver):
    """Tests that the solver initializes and reports the correct number of joints."""
    assert solver is not None
    assert solver.num_joints == 6  # Adjust this number based on your robot

def test_fk_ik_consistency(solver):
    """
    Tests if IK can solve for a pose generated by FK.
    This is a fundamental sanity check.
    """
    # An arbitrary set of joint angles
    joint_angles = np.deg2rad([10, 20, -30, 40, -50, 60])
    
    # 1. Use Forward Kinematics to get the public tool-tip pose.
    fk_matrix = solver.fk_matrix(joint_angles)
    fk_translation = fk_matrix[:3, 3]
    fk_rotation_flat = fk_matrix[:3, :3].flatten()

    assert fk_translation is not None, "FK calculation failed"

    # 2. Use Inverse Kinematics to solve for that pose
    # We use the original angles as the initial guess to get the same solution back
    ik_solution = solver.solve_pose(fk_translation, fk_rotation_flat, seed=joint_angles)

    assert ik_solution is not None, "IK solution not found for a valid FK pose"
    
    # 3. Check if the IK solution is very close to the original joint angles
    assert np.allclose(joint_angles, ik_solution, atol=1e-6), "FK -> IK -> FK round trip failed"

def test_batch_solver(solver):
    """Tests the high-performance batch solver on a short path."""
    # Define joint-space waypoints that stay within the known limits
    waypoints = np.array([
        np.zeros(solver.num_joints),
        np.array([0.05, -0.05, 0.03, 0.01, -0.01, 0.0]),
        np.array([0.1, -0.1, 0.06, 0.02, -0.02, 0.01]),
    ])

    # Convert to public Cartesian tool poses.
    path_points = []
    target_orientations = []
    for joint_angles in waypoints:
        pose = solver.fk_matrix(joint_angles)
        path_points.append(pose[:3, 3])
        target_orientations.append(pose[:3, :3])

    path_solutions = solver.solve_path_batch(path_points, waypoints[0], target_orientations=target_orientations)

    assert path_solutions is not None, "Batch solver failed to find a solution"
    assert path_solutions.shape == (len(waypoints), solver.num_joints), "Batch solver returned incorrect shape"
    # Confirm the solver follows the intended joint-space path
    assert np.allclose(path_solutions[-1], waypoints[-1], atol=1e-5), "Batch solver deviated from expected joint configuration"
